"""Inference primitives for the IP Webcam classroom demonstration."""

from .detectors import (
    DEFAULT_HELMET_CLASSES,
    Detection,
    FaceDetection,
    HelmetDetector,
    LetterboxTransform,
    NanoDetPersonDetector,
    PersonDetector,
    YoloHelmetOnnxDetector,
    YuNetFaceDetector,
    create_ort_session_options,
)
from .face_recognition import (
    DEFAULT_COSINE_MARGIN,
    DEFAULT_COSINE_THRESHOLD,
    FaceGallery,
    FaceMatch,
    SFaceEncoder,
    StudentRecord,
    cosine_similarity,
    load_roster_csv,
    normalize_embedding,
)
from .geometry import BBox, area, center, containment, iou
from .helmet_status import (
    HelmetHeuristicConfig,
    HelmetStatus,
    HelmetStatusEstimator,
    PersonAssociation,
    associate_faces_to_people,
    associate_heads_to_people,
    associate_people_faces_heads,
    classify_helmet_status,
)
from .processor import (
    ClassroomFrameProcessor,
    ClassroomProcessorConfig,
    coerce_processor_config,
    create_default_processor,
)
from .tracking import IoUTracker, TrackedDetection

__all__ = [
    "BBox",
    "ClassroomFrameProcessor",
    "ClassroomProcessorConfig",
    "DEFAULT_COSINE_MARGIN",
    "DEFAULT_COSINE_THRESHOLD",
    "DEFAULT_HELMET_CLASSES",
    "Detection",
    "FaceDetection",
    "FaceGallery",
    "FaceMatch",
    "HelmetDetector",
    "HelmetHeuristicConfig",
    "HelmetStatus",
    "HelmetStatusEstimator",
    "IoUTracker",
    "LetterboxTransform",
    "NanoDetPersonDetector",
    "PersonAssociation",
    "PersonDetector",
    "SFaceEncoder",
    "StudentRecord",
    "TrackedDetection",
    "YoloHelmetOnnxDetector",
    "YuNetFaceDetector",
    "area",
    "associate_faces_to_people",
    "associate_heads_to_people",
    "associate_people_faces_heads",
    "center",
    "classify_helmet_status",
    "containment",
    "cosine_similarity",
    "coerce_processor_config",
    "create_default_processor",
    "create_ort_session_options",
    "iou",
    "load_roster_csv",
    "normalize_embedding",
]
